# Setze das Build-Image auf die neueste Version von Nixpacks
buildImage = "ghcr.io/railwayapp/nixpacks:latest"

[phases.setup]
# Node Version
node_version = "24.11.1"

# Package Manager
package_manager = "pnpm"

# Optional: Fixiert die Nixpkgs-Version f√ºr Konsistenz
nixpkgsArchive = "11cb3517b3af6af300dd6c055aeda73c9bf52c48"
